# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 264fd2157e07edfec6205d3b484667cd5bb41fa15e86915faaec9a2bce6ac61959b70233ac2f1a93b435983b68dcba1e800a63f55b312694c87166a3e6cabab2

test:
  secret_key_base: bdb7d07de1e7e7f5055d2732c6891ca71e379943f41d9ae3698cefbc3cc5c1808151455933f070a54bd80e2dbea065cd9ba0443bf11560e1381866d294db2ae6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
